### ISSUE TITLE
Background bug in Safari and Edge

### ISSUE THREAD

**Issue by ghost** [NigelOToole/angled-edges#2]
Hi! First of all, thanks for creating this. It's easy to use and looks great for my project in Chrome and Firefox. In Safari and Edge, though, I'm getting a white background-color for the angled divs. This isn't coming from my styles. I've published [screenshot](https://imgur.com/a/x4Zms) of the bug.

Any experience with this?

**Comment by deansimcox** [comment]
Not sure if you ever figured it out, but I'm pretty sure those white bars come from the fallback code that uses pseudo ::before and ::after elements.
So you can either pass in a different colour to the sass mixin, like `@include angle-edge(..., $fallback-color: red);`.
Or you can remove that whole fallback section altogether, and other browsers will just fallback to non-angled lines
