### ISSUE TITLE
Angles not being properly calculated

### ISSUE THREAD

**Issue by mseymour** [NigelOToole/angled-edges#5]
I've been trying to implement this in a personal project that I am working on that I would like to have consistent angled areas throughout to match personal branding.

As an example:

![Screen Shot 2019-03-28 at 1 11 21 AM](https://user-images.githubusercontent.com/188480/55129597-6baa2380-50f6-11e9-80a1-5f3633d114aa.png)

The angle in the overlaid image (lower faded blue triangle) is at 12°, and in my Sass code, I am using the include like this:

```sass
  padding: 5% 0 11.5%;
  @include angle-edge($angle: 12, $angle-position-y: 'bottom', $angle-position-x: 'right', $angle-position-bottom-x: 'left');
  width: 100%;
```

I found that in order to get it as close to my design as possible, I would have to bring it down to around 9.5°, but it's not quite there:

![Screen Shot 2019-03-28 at 1 15 32 AM](https://user-images.githubusercontent.com/188480/55129740-060a6700-50f7-11e9-8fd9-c0ed013d7823.png)

I am not totally sure, but would `convertDegToVW()` need to be changed to make the angles more accurate? Or is this a case of something wrong with my styles mucking up the clipping path?

Thanks!

**Comment by NigelOToole** [comment]
Hi Mark
Its hard to diagnose the issue without being able to inspect the code but I would try creating a reduced test case first by removing as much styling as possible. Something like the uneven padding may be affecting it in some way. Its also possible the calculations in convertDegToVW() are off so I think some trial and error is needed. 
Please let me know how you get on.
